[workspace]
members = [
    "unwrap_check",
    "mpsc_blocking_send",
    "large_futures",
    "index_access_check",
    "tokio_time_interval"
]

[workspace.dependencies]
dylint_linting = "3.0.0"
dylint_testing = "3.0.0"
